### ISSUE TITLE
import third party libraries

### ISSUE THREAD

**Issue by pittavini** [jenkinsci/workflow-cps-global-lib-plugin#12]
So I added the code snippet that was added to the tutorial;

@Grab('org.apache.commons:commons-math3:3.4.1')
import org.apache.commons.math3.primes.Primes
etc ...

I am getting:
java.lang.NoClassDefFoundError: org/apache/ivy/core/settings/IvySettings

I am using the 2.2 version of the plugin, in .groovy I guess the library is downloaded, I am new to groovy and the plugin so forgive me for silly question:
[admpittavini@iddevci apache]$ find .
.
./ivy-4.xml.original
./ivydata-4.properties
./ivy-4.xml
./ivy-9.xml.original
./ivydata-9.properties
./ivy-9.xml
./ivy-3.xml.original
./ivydata-3.properties
./ivy-3.xml

Any idea what could be the cause?

**Comment by jglick** [comment]
See #9, and use JIRA.
