### ISSUE TITLE
Feature: external git repo for shared libs

### ISSUE THREAD

**Issue by francisdb** [jenkinsci/workflow-cps-global-lib-plugin#3]
We would like to store our pipeline libs in github instead of the internal Jenkins git.

**Comment by gtheraud** [comment]
@francisdb : personnaly I created a git repository in private gitlab and configure hook on each push. The hook triggers a job called `update-pipeline-library` in jenkins that simply does : 
```shell
cd /var/jenkins_home/workflow-libs/ 
rm -rf ./*
wget -qO- http://www.gitlab.com/namespace/pipeline-library/repository/archive.tar.gz | tar xvz --strip-components=1
```

I guess you could do the same with github.

**Comment by francisdb** [comment]
Interesting solution @gtheraud 
Will probably set that up as well

**Comment by StephenKing** [comment]
So you wouldn't consider it bad practice, if I synchronize the `workflow-libs/` directory on the master directly in the file system with my Github repo e.g. through Chef?

**Comment by Woland2k** [comment]
Here is a way to change where global pipeline scripts are stored, so for instance you can use github instead of internal git:
https://github.com/cloudbees/jenkins-scripts/blob/master/pipeline-global-lib-init.groovy

**Comment by StephenKing** [comment]
Nice! Is there any way to execute this inside a job (to immediately update it, once a change is pushed to github)?

Nevertheless, it seems that any way to keep the workflow-lib/ dir up to date should work (chef, cron, etc). Good to know.

**Comment by Woland2k** [comment]
Yes, I believe you can setup a job that runs every time changes are made and merges latest changes to local git. Here is some more info on it: https://github.com/beedemo-sa/workflowLibs

**Comment by jglick** [comment]
See #10, and use JIRA.
