### ISSUE TITLE
Feature: Ability to specify source ref for shared libs

### ISSUE THREAD

**Issue by crussell52** [jenkinsci/workflow-cps-global-lib-plugin#4]
It would be _amazing_ if we could configure the source ref (branch, tag, sha1) for the shared libs.  This would allow for versioning of the scripts lib in a sane way.

In its simplest form, it would be defined in global settings. It would allow:
1.    use of version tags/branches to control deployments of script lib changes.
2.    Quick rollback to an earlier revision/version if newly deployed script lib changes are found to be detrimental.

A more robust implementation would include a project-level override.  This would allow:
1.    Lock (or rollback) a particular job to a script library version.
2.    Progressively update jobs to use a newer script library version instead of all at once.

**Comment by crussell52** [comment]
This would be even better, if combined with https://github.com/jenkinsci/workflow-cps-global-lib-plugin/issues/3

**Comment by jglick** [comment]
See #10, and use JIRA.
