### ISSUE TITLE
how to write tests for shared groovy code?

### ISSUE THREAD

**Issue by alexdean** [jenkinsci/workflow-cps-global-lib-plugin#5]
i'm trying to figure out how to write unit tests for shared workflow code i manage via this plugin.

**disclaimer: i'm very new to groovy. i might be missing something that seems obvious.**

so far i've stubbed in a layout like:

```
gradlew
build.gradle
src/
test/
vars/
```

and set up a build script like

```groovy
// ./build.gradle
apply plugin: "groovy"

version = "1.0"
description = "jenkins workflow libs"

// Spock works with Java 1.5 and above
sourceCompatibility = 1.5

repositories {
  // Spock releases are available from Maven Central
  mavenCentral()
  // Spock snapshots are available from the Sonatype OSS snapshot repository
  maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
}

sourceSets {
  main {
    groovy {
      srcDirs = ['src']
    }
  }

  test {
    groovy {
      srcDirs = ['test']     
    }
  }
}

dependencies {
  compile "org.codehaus.groovy:groovy-all:2.4.1"
  testCompile "org.spockframework:spock-core:1.0-groovy-2.4"
}
```

this lets me create unit tests for the classes i define in `src/` using the [spock test framework](https://github.com/spockframework/spock).

i'm now trying to understand how i should write tests for the code in `vars/`. it should be easy enough to develop some mock objects which can provide the built-in methods that are normally provided by the plugin (`sh`, `git`, etc), but i'm unsure how to structure the mock and how to load it during a test run.

I want to be able to write tests like "when I invoke a build script (defined in var/something.groovy) in a certain way, i expect `sh` to be called with some parameters."

I need to be able to write tests for these scripts, since they'll be the basis for numerous other pipeline projects. We need to be able to detect regressions in these scripts automatically.

Please provide some guidance on how I should proceed here.

**Comment by zhelyan** [comment]
+1

**Comment by jglick** [comment]
Use JIRA. There is already an open RFE for testing Pipeline script.
