### ISSUE TITLE
Error executing functions when multiple scripts are used

### ISSUE THREAD

**Issue by selste** [jenkinsci/workflow-cps-global-lib-plugin#6]
Hi,
i'm running this Plugin (Version 2.0) with Jenkins 2.10 on Windows Server 2008 R2 with Tomcat 8.0

Simply following the README.md i created an 'acme.groovy' file and put it into the 'workflow-libs/vars' subdirectory, defined a Pipeline job and the output is as expected.
I then added another script, 'helloWorld.groovy', put it in the same subdirectory, added it to the job and received an error on execution:

`java.lang.NoSuchMethodError: No such DSL method 'helloWorld' found among [archive, bat, build, catchError, checkout, deleteDir, dir, echo, emailext, emailextrecipients, error, fileExists, findFiles, git, input, isUnix, load, mail, node, parallel, properties, pwd, readFile, readManifest, readMavenPom, readProperties, readTrusted, retry, sh, sleep, splitTests, stage, stash, step, svn, timeout, tool, touch, unarchive, unstash, unzip, waitUntil, withEnv, wrap, writeFile, writeMavenPom, ws, zip]
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:108)
[...]`

From the documentation i'd expect to be able to have an arbitrary number of scripts available automatically but that doesn't seem to be the case.

**Comment by lucavitucci** [comment]
Same for me, Debian machine, same version

**Comment by emerout** [comment]
Make sure you declare one function "call" in your helloWorld.groovy file :
```
def call() {
   // some code
}
```
Then call it in your job:
`helloWorld()`

**Comment by selste** [comment]
Hmm,
using Version 2.1 of the plugin now ... works, but with one - minor - issue:
The first script
`// vars/hello.groovy
def call(name) {
    echo "Hello, ${name}"
}`
is picked up immediatly from a running Jenkins, but when i add a second script
`// vars/goodbye.groovy
def call(name) {
    echo "Goodbye, ${name}"
}`
the error appears again. Only after restarting Jenkins does the error disappear and both scripts get executed.
I can live with that, it's just a bit of a nuisance ...

**Comment by jglick** [comment]
Please use JIRA.
